* <2017-10-31 Tue>
Finally talked to a friend about the shared code I was using (mostly for the context system that I used).
I'll start implementing a basic version of the textile and see how far I can get without needing context, then I'll can start pulling stuff in.



* <2017-10-30 Mon>
-- Some notes from my experiments with jupyter notebooks.

I was getting some python-version errors. [[https://github.com/millejoh/emacs-ipython-notebook/issues/176#issuecomment-305747009][These steps]] worked.
So now I can start Jupyter's repl-like console.

If I want to automate the startup later, it might be easier to script outside of Emacs (my emacs start-up time is long enough already).
I want to explore the org-mode integrations some more.

What does Jupyter do well? How can I integrate it into the documentation/presentation process? I'll ask T- on Weds.

Also, I found this [[https://blog.jupyter.org/the-continued-existence-of-the-emacs-ipython-notebook-54bd1c371d57][blog post]] on the jupyter blog by the Emacs jupyter maintainer. A short study on how development communities handle overlapping projects and naming conventions.
